disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "logPhile"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "January 2, 2006"
  # logo = "img/logo.png"
  secondaryLogo = "logphile-avatar.jpg"
  description = "Lorum ipsum lorum ipsum"
  copyright = "&copy; 2025 logPhile. All Rights Reserved."

 [params.author]
   name = "Phil Boyce"
   email = "phil@logphile.com"
   image = "logphile-avatar.jpg"
   imageQuality = 96
   headline = "Cloud & IT Professional"
#bio = "A little bit about you"
   links = [     
     { github = "https://github.com/logphile" },
     { linkedin = "https://www.linkedin.com/in/phil-boyce" },
     { x-twitter = "https://x.com/LogPhile" },
     { email = "mailto:phil@logphile.com" },
   ]
